management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
  endpoint:
    env:
      enabled: true
spring:
  datasource:
    url: ${cloud.services.tracker-database.connection.jdbcurl:jdbc:h2:mem:tracker_dev}
    username: ${cloud.services.tracker-database.connection.username:sa}
    password: ${cloud.services.tracker-database.connection.password:}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true